### ISSUE TITLE
Validate value via pointer

### ISSUE THREAD

**Issue by jeromegn** [Stranger6667/jsonschema#365]
In our use case, we're accepting small patches to a JSON document and we'd like to be able to validate the changed path only.

From a public API standpoint, we'd have our schema(s) and would be able to pass a pointer to a function to validate only the valued changed at the pointer.

Looking at the internal API structure, I don't think this would be too hard. If this is something that might benefit others, then I could make a PR.

I'd like some feedback on the idea about its usefulness and feasibility!

**Comment by Stranger6667** [comment]
Hi! Sorry for the long delay, but it is solvable now. See [this comment](https://github.com/Stranger6667/jsonschema/issues/432#issuecomment-2564830152). There are a few things to improve in the API and I'll keep track of it in #432.
