### ISSUE TITLE
[Feature Request] Meta-schema validation

### ISSUE THREAD

**Issue by n0madsky** [Stranger6667/jsonschema#442]
Hello, I'm wondering if we can make a function that just validates the JSON Schema itself, and not actually compile it into a `JSONSchema`, I currently just need to validate that the JSONSchema Received is valid, and doesn't need to actually use the schema itself. 

I'm happy to open a Pull Request for this, since there seem to be existing functionality that already does this.

**Comment by Stranger6667** [comment]
There is already a meta schema that does exactly this. I.e. you can use any of [those](https://github.com/Stranger6667/jsonschema-rs/tree/master/jsonschema/meta_schemas) to validate JSON Schemas. Internally, `jsonschema` contains such meta-validators [here](https://github.com/Stranger6667/jsonschema-rs/blob/master/jsonschema/src/compilation/options.rs#L166) but they are not public
