### ISSUE TITLE
jsonschema should re-export `referencing::Error`

### ISSUE THREAD

**Issue by mplanchard** [Stranger6667/jsonschema#614]
`Resource` is re-exported in `jsonschema`, but in order to create one, one has to call `Resource::from_content()`, which returns a `Result<Resource, referencing::Error>`. It is impossible to access `referencing::Error` in any way that I can see form the `jsonschema` crate, so it becomes necessary to import `referencing` as well, ensuring version and type parity.

It would be much more convenient if either all of `referencing` were re-exported somewhere, or at least some `referencing` namespace was provided in which the `Error` could be accessed.

**Comment by Stranger6667** [comment]
Makes sense, that's an oversight. Thank you so much for reporting it
