### ISSUE TITLE
[Python] Validation error when upgrading from 0.18.x to 0.26.0

### ISSUE THREAD

**Issue by chillswim** [Stranger6667/jsonschema#629]
Hello, 
changing the validator instantiation from (in 0.18.x):
```python
yaml_validator = jsonschema_rs.JSONSchema(schema)
``` 

to (in 0.26.0):
```
yaml_validator = jsonschema_rs.Draft7Validator(schema)
# or yaml_validator = jsonschema_rs.validator_for(schema)
```

raises the following error:
```
yaml_validator = jsonschema_rs.Draft7Validator(schema)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jsonschema_rs.ValidationError: Resource 'https://json-schema.org/draft-07/schema' is not present in a registry and retrieving it failed: error sending request for url (https://json-schema.org/draft-07/schema)

Failed validating in schema

On instance:
    null
```

I can correctly curl the URL present in the error. I haven't changed the schema.

**Comment by Stranger6667** [comment]
Hi! Could you, please, share the schema? at least partially, so I can reproduce it locally

**Comment by chillswim** [comment]
Hi, this is a minimal schema that triggers the error. If I remove the $schema both the `jsonschema_rs.Draft7Validator` and the  `jsonschema_rs.validator_for` work.

```json
{
    "$schema": "https://json-schema.org/draft-07/schema", 
    "definitions": {
        "SomeObject": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "required": [
                "name"
            ],
            "additionalProperties": false
        },
        "SomeOtherObject": {
            "type": "string",
            "enum": [
                "foo",
                "baz",
                "bar",
                "static"
            ]
        }
    },
    "oneOf": [
        {
            "$ref": "#/definitions/SomeObject"
        },
        {
            "$ref": "#/definitions/SomeOtherObject"
        }
    ]
}
```

Thanks

**Comment by Stranger6667** [comment]
Thanks! I think the issue is that the canonical `$schema` for Draft 7 is `http://json-schema.org/draft-07/schema#` (note "http") and it is not treated as equivalent to `https://json-schema.org/draft-07/schema`. I am going to fix it soon

**Comment by Stranger6667** [comment]
I think that `jsonschema` should signal the error as it is not a canonical `$schema` value. I.e. this SHOULD (as per spec) be treated as a normalized URI and URIs with different schemes are not equivalent.
