### ISSUE TITLE
Resolving references can fail if id uses a fragment

### ISSUE THREAD

**Issue by jrudolph** [Stranger6667/jsonschema#640]
This is a follow up to #547.

This is another case where the URL resolution fails because the base address contains a fragment when resolution is attempted. In this case it's triggered by an `$id` field containing a fragment.

#633 contains a one line change that triggers the bug.

**Comment by Stranger6667** [comment]
Hi @jrudolph 

Sorry for the delay! The issue is fixed in `0.28.1`. I hope that I got this one right this time :)
