### ISSUE TITLE
python: Add instance and kind from ValidationError

### ISSUE THREAD

**Issue by jpmckinney** [Stranger6667/jsonschema#650]
I see the Rust crate's ValidationError has these fields: https://github.com/Stranger6667/jsonschema/blob/b8eef873017a4ce84eb3281965ce7a2791f95e51/crates/jsonschema/src/error.rs#L17-L26

`instance` and `kind` would be very useful in the Python package's ValidationError, to be able to construct our own error messages (like how fmt::Display uses the `kind`) and to add other logic related to the `kind`.

https://github.com/Stranger6667/jsonschema/blob/b8eef873017a4ce84eb3281965ce7a2791f95e51/crates/jsonschema-py/python/jsonschema_rs/__init__.pyi#L35-L38

**Comment by Stranger6667** [comment]
That's awesome! For the next minor version, I was thinking about overhauling everything related to errors, including customizing error messages for both, Rust & Python.

I think that exposing these fields is a viable option, however, I'd like to spend some extra time on design to ensure features like internationalization (see #382) are ergonomic enough to use.

**Comment by Stranger6667** [comment]
Added these two attributes, I hope they will help with your use case :) I was also thinking that later there could be extra attributes from the Rust’s enum, but it will require some work

**Comment by jpmckinney** [comment]
Thank you!

Yes, things like AdditionalProperties.unexpected and Required.property would be very useful to retain.

For things like ExclusiveMinimum.limit, I could use schema_path to look up the limit, but for the others mentioned, I’d need to reevaluate the validation keyword to get the values needed to construct my own error messages, etc.

**Comment by Stranger6667** [comment]
I've spent a bit of time on [complex enums](https://pyo3.rs/v0.23.3/class.html?highlight=enum#complex-enums), but it didn't work straight away because I wanted to keep inner exceptions (e.g. in `PropertyNames`). I think it is doable but I need to dig deeper, hence I kind of postponed this implementation in favor of a simpler one.

> I’m wondering whether #[derive(FromPyObject)] on the Rust enum would preserve the struct fields? (Instead of https://github.com/Stranger6667/jsonschema/pull/654 which uses a simple Python-style enum for the kind exposed in Python).

Assuming you meant `IntoPyObject` (given the conversion direction we need) I think it could be the way to go. I'll try it out soon

**Comment by Stranger6667** [comment]
This one should work - https://github.com/Stranger6667/jsonschema/pull/656

I am going to add some more details into referencing errors and such, so it can be properly introspected.

**Comment by Stranger6667** [comment]
Seems like `PyO3` does not support nested enums needed for `ReferencingError` & `PropertyNames` :( I'll investigate more and open an issue in `PyO3` if needed. Right now these variants will have limited introspection. But hopefully, it should still be possible to build custom error messages based on that limited "inner" message (likely hacky though)

**Comment by jpmckinney** [comment]
Awesome! 🎉
